### ISSUE TITLE
non zero diagonal similarity Matrix

### ISSUE THREAD

**Issue by torki-hossein** [dvl-tum/group_loss#5]
Hi, as you said in the dynamic file and also in the original paper the similarity matrix (W) must has zero diagonal but in this implementation you don't set zero for diagonal element of W.
as a proposal for correction you can use below line in the set_negative_to_zero method in the gtg module:
W=W*(1 - torch.eye(W.shape[0], W.shape[0])).to(self.device)
is it right?

**Comment by CoinCheung** [comment]
Hi, 

Why do you close this? I have same question, have you ever figure this out?
